Updated earthlyw with bash-version

diff --git a/earthlyw b/earthlyw
--- a/earthlyw
+++ b/earthlyw
@@ -30,7 +30,7 @@ EXECUTABLE="${CACHE_DIR}/${EXECUTABLE_NAME}"
 
 # If executable does not exist, fetch it
 if [[ ! -x "${EXECUTABLE}" ]]; then
-  echo "Cache is older than 1 month, fetching latest version"
+  echo "Cache is older than 1 month, fetching latest version" >&2
 
   # Fetch latest release information
   DATA_FILE=$(mktemp --suffix=.json)
@@ -40,7 +40,7 @@ if [[ ! -x "${EXECUTABLE}" ]]; then
   DOWNLOAD_URL=$(jq -r ".assets[] | select(.name == \"${EXECUTABLE_NAME}\") | .browser_download_url" "${DATA_FILE}")
 
   if [[ -z "${DOWNLOAD_URL}" ]]; then
-    echo "Failed to find download URL for ${EXECUTABLE_NAME}"
+    echo "Failed to find download URL for ${EXECUTABLE_NAME}" >&2
     exit 1
   fi
 
